### ISSUE TITLE
Singleton approach

### ISSUE THREAD

**Issue by jean9696** [tarikjabiri/dxf#18]
Hi,

For now almost every objects are singletons, why do we need this ? Can we add a way to `destroy` the instance ? Or maybe just make `DxfWriter` scoped ?

**Comment by jean9696** [comment]
For me having singletons here is a bad thing, it's not scoped so we want instanciate 2 or more `DxfWriter`, it's only viable for a script, but on a node server or in the browser it will cause a lot of troubles.
I will see if I can make a PR.

**Comment by tarikjabiri** [comment]
Yeah but I don't want to break the API
Is it ok to make breaking changes 🤔

**Comment by jean9696** [comment]
You can make breaking change it's your library 😁 
And breaking changes are ok if you make a new **major** version
